// <auto-generated />
using System;
using Infrastructure.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523003657_AddAiProviderConfig")]
    partial class AddAiProviderConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_RefreshToken_UserId_RevokedAt");

                    b.ToTable("RefreshToken", "auth");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email");

                    b.ToTable("User", "auth");
                });

            modelBuilder.Entity("Domain.Catalog.Fibra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("currency");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("InvestorUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("investor_url");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("market");

                    b.Property<string>("NameVariants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_variants");

                    b.Property<string>("ReportsUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("reports_url");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("sector");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("short_name");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("site_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.Property<string>("YahooTicker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("yahoo_ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("UX_Fibra_Ticker");

                    b.ToTable("Fibra", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Uno",
                            InvestorUrl = "https://fibra.uno/inversionistas",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Uno\",\"FUNO\"]",
                            Sector = "Diversificado",
                            ShortName = "Fibra Uno",
                            SiteUrl = "https://fibra.uno",
                            State = "Active",
                            Ticker = "FUNO11",
                            YahooTicker = "FUNO11.MX"
                        },
                        new
                        {
                            Id = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Danhos",
                            InvestorUrl = "https://fibradanhos.com.mx/ri",
                            Market = "BMV",
                            NameVariants = "[\"Danhos\",\"DANHOS\"]",
                            Sector = "Comercial",
                            ShortName = "Danhos",
                            SiteUrl = "https://fibradanhos.com.mx",
                            State = "Active",
                            Ticker = "DANHOS13",
                            YahooTicker = "DANHOS13.MX"
                        },
                        new
                        {
                            Id = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Terra",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Terra\",\"TERRA\"]",
                            Sector = "Industrial",
                            ShortName = "Terra",
                            SiteUrl = "https://fibra-terra.com",
                            State = "Active",
                            Ticker = "TERRA13",
                            YahooTicker = "TERRA13.MX"
                        },
                        new
                        {
                            Id = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Macquarie",
                            InvestorUrl = "https://fibramacquarie.com.mx/ri",
                            Market = "BMV",
                            NameVariants = "[\"Fibra MQ\",\"Macquarie\",\"FIBRAMQ\"]",
                            Sector = "Industrial",
                            ShortName = "FibraMQ",
                            SiteUrl = "https://fibramacquarie.com.mx",
                            State = "Active",
                            Ticker = "FIBRAMQ12",
                            YahooTicker = "FIBRAMQ12.MX"
                        },
                        new
                        {
                            Id = new Guid("7882f6d3-304f-5de6-2211-60508c2021c6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Monterrey",
                            InvestorUrl = "https://fibramty.com/inversionistas",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Monterrey\",\"FibraMTY\",\"FMTY\"]",
                            Sector = "Industrial",
                            ShortName = "Fibra MTY",
                            SiteUrl = "https://fibramty.com",
                            State = "Active",
                            Ticker = "FMTY14",
                            YahooTicker = "FMTY14.MX"
                        },
                        new
                        {
                            Id = new Guid("38a237f5-9065-f4ec-7b19-c116a9642c6f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Inn",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Inn\",\"FINN\"]",
                            Sector = "Hotelero",
                            ShortName = "Fibra Inn",
                            SiteUrl = "https://fibrainn.com.mx",
                            State = "Active",
                            Ticker = "FINN13",
                            YahooTicker = "FINN13.MX"
                        },
                        new
                        {
                            Id = new Guid("6cbe26c2-2ed0-6df0-6242-1c78d011e9fc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Hotel",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Hotel\",\"FIHO\"]",
                            Sector = "Hotelero",
                            ShortName = "Fibra Hotel",
                            SiteUrl = "https://fibrahotel.com",
                            State = "Active",
                            Ticker = "FIHO12",
                            YahooTicker = "FIHO12.MX"
                        },
                        new
                        {
                            Id = new Guid("ae26cf6f-b4dc-be5a-3355-f4f4a9165499"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Vesta",
                            InvestorUrl = "https://fibravesta.com/ri",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Vesta\",\"VESTA\"]",
                            Sector = "Industrial",
                            ShortName = "Vesta",
                            SiteUrl = "https://fibravesta.com",
                            State = "Active",
                            Ticker = "VESTA15",
                            YahooTicker = "VESTA.MX"
                        },
                        new
                        {
                            Id = new Guid("d96dd899-9a7e-3c95-a9ba-bbf62577a241"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Hotel City Express",
                            Market = "BMV",
                            NameVariants = "[\"Hotel City Express\",\"HCITY\",\"HC\"]",
                            Sector = "Hotelero",
                            ShortName = "HC",
                            SiteUrl = "https://hcity.com.mx",
                            State = "Active",
                            Ticker = "HCITY17",
                            YahooTicker = "HCITY.MX"
                        },
                        new
                        {
                            Id = new Guid("3129ee4f-d156-04c8-a03f-42bdc468ff27"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Educa",
                            InvestorUrl = "https://www.fibraeduca.com/invertir",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Educa\",\"EDUCA\",\"EDUCA18\"]",
                            ReportsUrl = "https://www.fibraeduca.com/reportes-financieros",
                            Sector = "Educativo",
                            ShortName = "Fibra Educa",
                            SiteUrl = "https://www.fibraeduca.com",
                            State = "Active",
                            Ticker = "EDUCA18",
                            YahooTicker = "EDUCA18.MX"
                        },
                        new
                        {
                            Id = new Guid("32377b6d-9244-a715-0279-2660cc6b62a5"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Prologis",
                            InvestorUrl = "https://www.fibraprologis.com/en-US/investors",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Prologis\",\"Prologis\",\"FIBRAPL\"]",
                            ReportsUrl = "https://www.fibraprologis.com/en-US/investors/financial-results",
                            Sector = "Industrial",
                            ShortName = "Prologis",
                            SiteUrl = "https://www.fibraprologis.com/en-US",
                            State = "Active",
                            Ticker = "FIBRAPL14",
                            YahooTicker = "FIBRAPL14.MX"
                        },
                        new
                        {
                            Id = new Guid("132f2dbd-1a77-3ca5-01eb-c65b7a03b14b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Upsite",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Upsite\",\"Upsite\",\"FIBRAUP\"]",
                            Sector = "Industrial",
                            ShortName = "Upsite",
                            SiteUrl = "https://fibra-upsite.com",
                            State = "Active",
                            Ticker = "FIBRAUP18",
                            YahooTicker = "FIBRAUP18.MX"
                        },
                        new
                        {
                            Id = new Guid("8d7ad206-8591-fd28-f33f-d0b887817b5c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Nova",
                            InvestorUrl = "https://www.fibra-nova.com/inversionistas/como-invertir",
                            Market = "BIVA",
                            NameVariants = "[\"Fibra Nova\",\"FNOVA\",\"FNOVA17\"]",
                            ReportsUrl = "https://www.fibra-nova.com/inversionistas/reportes-trimestrales",
                            Sector = "Diversificado",
                            ShortName = "Fibra Nova",
                            SiteUrl = "https://www.fibra-nova.com",
                            State = "Active",
                            Ticker = "FNOVA17",
                            YahooTicker = "FNOVA17.MX"
                        },
                        new
                        {
                            Id = new Guid("32418186-9e2c-942b-8f4a-1e61388760a4"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Plus",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Plus\",\"FPLUS\",\"FPLUS16\"]",
                            ReportsUrl = "https://www.fibraplus.mx/es/financiera/trimestrales",
                            Sector = "Diversificado",
                            ShortName = "Fibra Plus",
                            SiteUrl = "https://www.fibraplus.mx",
                            State = "Active",
                            Ticker = "FPLUS16",
                            YahooTicker = "FPLUS16.MX"
                        },
                        new
                        {
                            Id = new Guid("933f9202-f943-0342-0e05-5cfd283a5bbc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Shop",
                            InvestorUrl = "https://fibrashop.mx/contacto/",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Shop\",\"FSHOP\",\"FSHOP13\"]",
                            ReportsUrl = "https://fibrashop.mx/informes-financieros/",
                            Sector = "Comercial",
                            ShortName = "Fibra Shop",
                            SiteUrl = "https://fibrashop.mx",
                            State = "Active",
                            Ticker = "FSHOP13",
                            YahooTicker = "FSHOP13.MX"
                        },
                        new
                        {
                            Id = new Guid("2f25d292-5a8d-a262-1cdc-093621c7471c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Next",
                            InvestorUrl = "https://fibranext.mx/investors",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Next\",\"NEXT\",\"NEXT25\"]",
                            ReportsUrl = "https://fibranext.mx/investors",
                            Sector = "Industrial",
                            ShortName = "Fibra Next",
                            SiteUrl = "https://fibranext.mx",
                            State = "Active",
                            Ticker = "NEXT25",
                            YahooTicker = "NEXT25.MX"
                        },
                        new
                        {
                            Id = new Guid("9797ad53-1324-9a81-6102-992b9f07e92c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra SOMA",
                            Market = "BIVA",
                            NameVariants = "[\"Fibra SOMA\",\"SOMA\",\"SOMA21\"]",
                            Sector = "Comercial",
                            ShortName = "Fibra SOMA",
                            SiteUrl = "https://fibrasoma.group",
                            State = "Active",
                            Ticker = "SOMA21",
                            YahooTicker = "SOMA21.MX"
                        },
                        new
                        {
                            Id = new Guid("17e765b2-df1e-6842-3dcf-ec7506563c89"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Storage",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Storage\",\"Storage\",\"STORAGE18\",\"U-Storage\"]",
                            ReportsUrl = "https://fibrastorage.com/repositorio-informacion-financiera/",
                            Sector = "Autoalmacenaje",
                            ShortName = "Fibra Storage",
                            SiteUrl = "https://fibrastorage.com",
                            State = "Active",
                            Ticker = "STORAGE18",
                            YahooTicker = "STORAGE18.MX"
                        },
                        new
                        {
                            Id = new Guid("055c422a-c2df-ec0f-ab61-2b5c3ede52c2"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "FHipo",
                            InvestorUrl = "https://fhipo.com/es/kit-para-inversionistas/",
                            Market = "BIVA",
                            NameVariants = "[\"FHipo\",\"Fideicomiso Hipotecario\",\"FHIPO\",\"FHIPO14\"]",
                            ReportsUrl = "https://fhipo.com/es/reportes-trimestrales/",
                            Sector = "Hipotecario",
                            ShortName = "FHipo",
                            SiteUrl = "https://fhipo.com/es/",
                            State = "Active",
                            Ticker = "FHIPO14",
                            YahooTicker = "FHIPO14.MX"
                        },
                        new
                        {
                            Id = new Guid("15d3465f-5ff4-a84c-c883-1dd381fd22f0"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "CFE Fibra E",
                            InvestorUrl = "https://cfecapital.com.mx/inversionistas",
                            Market = "BMV/BIVA",
                            NameVariants = "[\"CFE Fibra E\",\"FCFE\",\"FCFE18\"]",
                            ReportsUrl = "https://cfecapital.com.mx/inversionistas",
                            Sector = "Infraestructura",
                            ShortName = "CFE Fibra E",
                            SiteUrl = "https://cfecapital.com.mx",
                            State = "Active",
                            Ticker = "FCFE18",
                            YahooTicker = "FCFE18.MX"
                        });
                });

            modelBuilder.Entity("Domain.Market.DailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("close");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("high");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("open");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("FibraId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_DailySnapshot_FibraId_Date");

                    b.ToTable("DailySnapshot", "market");
                });

            modelBuilder.Entity("Domain.Market.Distribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPerUnit")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("amount_per_unit");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("FibraId", "PaymentDate")
                        .IsUnique()
                        .HasDatabaseName("UIX_Distribution_FibraId_PaymentDate");

                    b.ToTable("Distribution", "market");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bbbb154-b518-66f0-6637-9b15850397a8"),
                            AmountPerUnit = 0.3100m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2021, 3, 15),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("249e2535-408e-e0db-90e4-602ea74bb40d"),
                            AmountPerUnit = 0.3150m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2021, 6, 14),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("00777343-ebe9-68f0-c0d9-1a972125742f"),
                            AmountPerUnit = 0.3180m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2021, 9, 13),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("3ccdc1eb-c781-6972-f073-fdd788cdb8b4"),
                            AmountPerUnit = 0.3200m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2021, 12, 13),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("2c2c6ef6-29bb-468b-4a60-b8f1a5aad69b"),
                            AmountPerUnit = 0.3300m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2022, 3, 14),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("134f77eb-4afc-4807-b139-36a64791d83f"),
                            AmountPerUnit = 0.3380m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2022, 6, 13),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("3e2dbc4b-6422-5059-49c3-9238a184ee2e"),
                            AmountPerUnit = 0.3420m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2022, 9, 12),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("2ca1aa7d-0958-4583-040a-646cf586ad96"),
                            AmountPerUnit = 0.3460m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2022, 12, 12),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("73cf3c5c-d05d-bdc0-e25c-15d18c654802"),
                            AmountPerUnit = 0.3500m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2023, 3, 13),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("5babaaff-7083-0205-c580-61ebd295fd10"),
                            AmountPerUnit = 0.3580m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2023, 6, 12),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("f1a4ecac-f36b-e733-a7fc-e5ed6053e6de"),
                            AmountPerUnit = 0.3620m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2023, 9, 11),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("84dbaa5b-e460-a15e-2431-442e56d44f0f"),
                            AmountPerUnit = 0.3660m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2023, 12, 11),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("1864e970-626f-abaa-0c24-77b72ff123bd"),
                            AmountPerUnit = 0.3680m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2024, 3, 18),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("5278bfd8-b8a0-ea29-bcf7-0ba402d7e924"),
                            AmountPerUnit = 0.3720m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2024, 6, 17),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("d8e7b864-fd0d-7a22-4a4a-4c46404a2544"),
                            AmountPerUnit = 0.3760m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2024, 9, 16),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("49a7be56-9ac0-c735-7674-f1a584e26f70"),
                            AmountPerUnit = 0.3800m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2024, 12, 16),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("b34cecad-3540-7d2b-5ea6-8000db9c5a0b"),
                            AmountPerUnit = 0.3610m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 3, 17),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("0712aff6-cf0f-55dd-a6dc-090e83c5233a"),
                            AmountPerUnit = 0.3720m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 6, 16),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("85a4ed94-b620-298c-c457-b124599fb3b7"),
                            AmountPerUnit = 0.3780m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("c36fa6a1-117f-9d25-a947-8d6ee00e30f4"),
                            AmountPerUnit = 0.3840m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("22ab0fa4-a568-68ec-cf8f-04d474d88988"),
                            AmountPerUnit = 0.1900m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2021, 3, 15),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("0137f687-5666-c94c-caeb-377119816221"),
                            AmountPerUnit = 0.1950m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2021, 6, 14),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("24260c3b-ef78-0968-6f3c-efe375b565e3"),
                            AmountPerUnit = 0.1980m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2021, 9, 13),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("ef00f014-3a95-0e27-a5fa-76badf3c49c5"),
                            AmountPerUnit = 0.2000m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2021, 12, 13),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("a2e5c597-0238-9607-c8de-c3df6d9e4f65"),
                            AmountPerUnit = 0.2020m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2022, 3, 14),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("dd6a1e53-d748-bb6a-a5bc-1742bcb8d5fb"),
                            AmountPerUnit = 0.2050m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2022, 6, 13),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("cff64c3f-d949-91fc-36e8-7dc331e611ec"),
                            AmountPerUnit = 0.2080m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2022, 9, 12),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("f5c73975-4c45-b1fe-bb1c-e9e913f488a4"),
                            AmountPerUnit = 0.2100m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2022, 12, 12),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("a9944cc5-75a9-4ccb-e53c-a64c9687c104"),
                            AmountPerUnit = 0.2100m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2023, 3, 13),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("ca11459c-c62d-01d5-e73d-2398c84b57ec"),
                            AmountPerUnit = 0.2130m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2023, 6, 12),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("3ea58762-31cb-1687-2b59-931ba80860d8"),
                            AmountPerUnit = 0.2160m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2023, 9, 11),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("6c96a62e-17ed-a8a8-6f86-1f4841b22da3"),
                            AmountPerUnit = 0.2180m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2023, 12, 11),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("a84e7f7c-9852-61d3-fb7d-9dc07eeda3ce"),
                            AmountPerUnit = 0.2180m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2024, 3, 18),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("aa044830-cfbd-bcf0-e79f-89c7287e8912"),
                            AmountPerUnit = 0.2200m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2024, 6, 17),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("e2877d0a-5fa4-1b33-ec8f-1740601a3c3d"),
                            AmountPerUnit = 0.2220m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2024, 9, 16),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("3cd135c0-6ef9-07d2-c58c-9f23c8f6d969"),
                            AmountPerUnit = 0.2250m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2024, 12, 16),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("3ad4a8a2-8e06-5923-aedd-25a49939ea84"),
                            AmountPerUnit = 0.2150m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 3, 17),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("ac5bb4bb-0719-2425-d621-5f823e9da129"),
                            AmountPerUnit = 0.2200m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 6, 16),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("e95c49b8-0da1-0cdb-9698-4ffee01cb629"),
                            AmountPerUnit = 0.2250m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("f2af8992-b244-6d43-9610-2f69c170477f"),
                            AmountPerUnit = 0.2300m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("e1815ccd-c2de-c8d3-0a78-46348657eab0"),
                            AmountPerUnit = 0.1500m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2021, 6, 14),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("aa379a05-ccf6-dd08-09a4-a4fa5a7225fd"),
                            AmountPerUnit = 0.1530m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2021, 9, 13),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("ed7b344a-e13d-5c8c-0159-09ccbf87835c"),
                            AmountPerUnit = 0.1550m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2021, 12, 13),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("662c2c1c-e08a-a6df-2c83-6331d8714653"),
                            AmountPerUnit = 0.1580m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2022, 3, 14),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("f0d429c6-9ba2-ca53-b252-1162a7e02a99"),
                            AmountPerUnit = 0.1600m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2022, 6, 13),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("1c20f71e-193b-f476-88b7-b056789186a4"),
                            AmountPerUnit = 0.1620m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2022, 9, 12),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("3641773c-175e-3176-5af6-d3c9cc43fee0"),
                            AmountPerUnit = 0.1640m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2022, 12, 12),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("7bfffaff-b5a1-0869-1ba2-a5b573b39dd3"),
                            AmountPerUnit = 0.1650m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2023, 3, 13),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("627ced36-69ac-91e8-7427-2824c2ef8221"),
                            AmountPerUnit = 0.1680m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2023, 6, 12),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("5233cae1-9172-0ef6-7c00-6ad251574aaf"),
                            AmountPerUnit = 0.1700m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2023, 9, 11),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("908677ac-2c56-9fbb-dae2-b610f6c491be"),
                            AmountPerUnit = 0.1720m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2023, 12, 11),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("520331f0-8890-6215-eaa3-5fbca55ed140"),
                            AmountPerUnit = 0.1730m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2024, 3, 18),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("08c47232-2945-58d3-e018-0c687cf9987d"),
                            AmountPerUnit = 0.1750m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2024, 6, 17),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("535537f5-bb64-3772-486d-be8ef4b150ac"),
                            AmountPerUnit = 0.1770m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2024, 9, 16),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("de21e159-a5ad-0c4f-eb7e-8bbb833a9cae"),
                            AmountPerUnit = 0.1790m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2024, 12, 16),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("52cae36d-59cc-bc56-cb33-cb5429192916"),
                            AmountPerUnit = 0.1750m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2025, 6, 16),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("8671a635-0d04-2660-ae19-dac73d60fd1b"),
                            AmountPerUnit = 0.1800m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("4f56248a-fe67-33bf-4033-6df6a608ca2b"),
                            AmountPerUnit = 0.1820m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("3e264b5f-5643-58fa-be69-21d0be470954"),
                            AmountPerUnit = 0.1100m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2021, 6, 14),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("546667b5-d9b5-8932-82fc-c2b4c7928d98"),
                            AmountPerUnit = 0.1150m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2021, 12, 13),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("ffa46d39-4893-5a33-b8c8-0417d48b73fb"),
                            AmountPerUnit = 0.1200m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2022, 6, 13),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("900c466e-b739-8bef-221e-cff787935af6"),
                            AmountPerUnit = 0.1250m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2022, 12, 12),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("2d5fcd74-962e-c0d6-f1f6-b8b25a0009b9"),
                            AmountPerUnit = 0.1300m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2023, 6, 12),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("62b96edf-b872-2f4b-0799-674cb585264a"),
                            AmountPerUnit = 0.1350m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2023, 12, 11),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("cda927f7-2ff8-a628-515d-42ae2fac8182"),
                            AmountPerUnit = 0.1400m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2024, 6, 17),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("12754f3b-2021-99c6-dc06-a413948bc0fd"),
                            AmountPerUnit = 0.1450m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2024, 12, 16),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("b2b41c08-7711-6ede-c2f0-8936c7a72828"),
                            AmountPerUnit = 0.1480m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("3fce78aa-5887-0f04-a1f3-ca1e7fcb4803"),
                            AmountPerUnit = 0.1520m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        });
                });

            modelBuilder.Entity("Domain.Market.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<decimal?>("DailyChange")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("daily_change");

                    b.Property<decimal?>("DailyChangePct")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("daily_change_pct");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("error_reason");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("last_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("week52_high");

                    b.Property<decimal?>("Week52Low")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("week52_low");

                    b.HasKey("Id");

                    b.HasIndex("FibraId", "CapturedAt")
                        .HasDatabaseName("IX_PriceSnapshot_FibraId_CapturedAt");

                    b.ToTable("PriceSnapshot", "market");
                });

            modelBuilder.Entity("Domain.News.AiModeConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mode");

                    b.Property<string>("PreviousMode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("previous_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("AiModeConfig", "ai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mode = "Off",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("Domain.News.AiProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("model_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("AiProviderConfig", "ai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelId = "gemini-2.5-flash",
                            Provider = "Gemini",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("Domain.News.BlocklistTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.HasIndex("Term")
                        .IsUnique()
                        .HasDatabaseName("IX_BlocklistTerm_Term");

                    b.ToTable("BlocklistTerm", "news");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e42a6f48-fd39-9fcb-9cdd-b32936d4151a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra óptica"
                        },
                        new
                        {
                            Id = new Guid("e05324fb-2c04-9389-41f6-a1dce885eba2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra optica"
                        },
                        new
                        {
                            Id = new Guid("33addac2-f65d-b0e1-616f-0b72e7aad6c3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra alimentaria"
                        },
                        new
                        {
                            Id = new Guid("93629cda-318e-f05f-94a4-49e87f7a07b3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra dietética"
                        },
                        new
                        {
                            Id = new Guid("3c3dbbea-5d57-c2e7-7395-0cef7bf9fba9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra dietetica"
                        },
                        new
                        {
                            Id = new Guid("c0166b06-2573-7815-6d80-6e448212bc1a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra muscular"
                        },
                        new
                        {
                            Id = new Guid("18288ba5-5469-5321-b116-12f462def773"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra textil"
                        },
                        new
                        {
                            Id = new Guid("01198b97-3348-19ce-d5a6-92bbde33ebeb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra de carbono"
                        },
                        new
                        {
                            Id = new Guid("e1e5c21c-7dcc-13b9-c5b2-065e293260cd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "internet fibra"
                        },
                        new
                        {
                            Id = new Guid("c2c16834-61c4-a329-acb9-3f601fe94781"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra de vidrio"
                        });
                });

            modelBuilder.Entity("Domain.News.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_summary");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_text");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("error_reason");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<string>("Snippet")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("snippet");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title");

                    b.Property<string>("TitleNormalized")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_normalized");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsArticle_Url");

                    b.HasIndex("TitleNormalized", "CapturedAt")
                        .HasDatabaseName("IX_NewsArticle_TitleNormalized_CapturedAt");

                    b.ToTable("NewsArticle", "news");
                });

            modelBuilder.Entity("Domain.News.NewsArticleFibra", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("news_article_id");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.HasKey("NewsArticleId", "FibraId");

                    b.HasIndex("FibraId")
                        .HasDatabaseName("IX_NewsArticleFibra_FibraId");

                    b.ToTable("NewsArticleFibra", "news");
                });

            modelBuilder.Entity("Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("Domain.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.News.NewsArticleFibra", b =>
                {
                    b.HasOne("Domain.News.NewsArticle", "NewsArticle")
                        .WithMany("FibraLinks")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.News.NewsArticle", b =>
                {
                    b.Navigation("FibraLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
