// <auto-generated />
using System;
using Infrastructure.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517011729_AddCatalogSchema")]
    partial class AddCatalogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_RefreshToken_UserId_RevokedAt");

                    b.ToTable("RefreshToken", "auth");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email");

                    b.ToTable("User", "auth");
                });

            modelBuilder.Entity("Domain.Catalog.Fibra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("currency");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("InvestorUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("investor_url");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("market");

                    b.Property<string>("NameVariants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_variants");

                    b.Property<string>("ReportsUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("reports_url");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("sector");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("short_name");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("site_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("UX_Fibra_Ticker");

                    b.ToTable("Fibra", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Uno",
                            InvestorUrl = "https://fibra.uno/inversionistas",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Uno\",\"FUNO\"]",
                            Sector = "Diversificado",
                            ShortName = "Fibra Uno",
                            SiteUrl = "https://fibra.uno",
                            State = "Active",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Danhos",
                            InvestorUrl = "https://fibradanhos.com.mx/ri",
                            Market = "BMV",
                            NameVariants = "[\"Danhos\",\"DANHOS\"]",
                            Sector = "Comercial",
                            ShortName = "Danhos",
                            SiteUrl = "https://fibradanhos.com.mx",
                            State = "Active",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Terra",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Terra\",\"TERRA\"]",
                            Sector = "Industrial",
                            ShortName = "Terra",
                            SiteUrl = "https://fibra-terra.com",
                            State = "Active",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Macquarie",
                            InvestorUrl = "https://fibramacquarie.com.mx/ri",
                            Market = "BMV",
                            NameVariants = "[\"Fibra MQ\",\"Macquarie\",\"FIBRAMQ\"]",
                            Sector = "Industrial",
                            ShortName = "FibraMQ",
                            SiteUrl = "https://fibramacquarie.com.mx",
                            State = "Active",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("7882f6d3-304f-5de6-2211-60508c2021c6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Monterrey",
                            InvestorUrl = "https://fibramty.com/inversionistas",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Monterrey\",\"FibraMTY\",\"FMTY\"]",
                            Sector = "Industrial",
                            ShortName = "Fibra MTY",
                            SiteUrl = "https://fibramty.com",
                            State = "Active",
                            Ticker = "FMTY14"
                        },
                        new
                        {
                            Id = new Guid("38a237f5-9065-f4ec-7b19-c116a9642c6f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Inn",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Inn\",\"FINN\"]",
                            Sector = "Hotelero",
                            ShortName = "Fibra Inn",
                            SiteUrl = "https://fibrainn.com.mx",
                            State = "Active",
                            Ticker = "FINN13"
                        },
                        new
                        {
                            Id = new Guid("6cbe26c2-2ed0-6df0-6242-1c78d011e9fc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Hotel",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Hotel\",\"FIHO\"]",
                            Sector = "Hotelero",
                            ShortName = "Fibra Hotel",
                            SiteUrl = "https://fibrahotel.com",
                            State = "Active",
                            Ticker = "FIHO12"
                        },
                        new
                        {
                            Id = new Guid("ae26cf6f-b4dc-be5a-3355-f4f4a9165499"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Vesta",
                            InvestorUrl = "https://fibravesta.com/ri",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Vesta\",\"VESTA\"]",
                            Sector = "Industrial",
                            ShortName = "Vesta",
                            SiteUrl = "https://fibravesta.com",
                            State = "Active",
                            Ticker = "VESTA15"
                        },
                        new
                        {
                            Id = new Guid("d96dd899-9a7e-3c95-a9ba-bbf62577a241"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Hotel City Express",
                            Market = "BMV",
                            NameVariants = "[\"Hotel City Express\",\"HCITY\",\"HC\"]",
                            Sector = "Hotelero",
                            ShortName = "HC",
                            SiteUrl = "https://hcity.com.mx",
                            State = "Active",
                            Ticker = "HCITY17"
                        },
                        new
                        {
                            Id = new Guid("cc194e75-e5a3-ee5e-0673-0f61be3fe509"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Plus",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Plus\",\"PLUS\"]",
                            Sector = "Diversificado",
                            ShortName = "Fibra Plus",
                            SiteUrl = "https://fibraplus.mx",
                            State = "Active",
                            Ticker = "PLUS18"
                        });
                });

            modelBuilder.Entity("Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("Domain.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
