// <auto-generated />
using System;
using Infrastructure.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519163418_AddNewsSchema")]
    partial class AddNewsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_RefreshToken_UserId_RevokedAt");

                    b.ToTable("RefreshToken", "auth");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email");

                    b.ToTable("User", "auth");
                });

            modelBuilder.Entity("Domain.Catalog.Fibra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("currency");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("InvestorUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("investor_url");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("market");

                    b.Property<string>("NameVariants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_variants");

                    b.Property<string>("ReportsUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("reports_url");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("sector");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("short_name");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("site_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.Property<string>("YahooTicker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("yahoo_ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("UX_Fibra_Ticker");

                    b.ToTable("Fibra", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Uno",
                            InvestorUrl = "https://fibra.uno/inversionistas",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Uno\",\"FUNO\"]",
                            Sector = "Diversificado",
                            ShortName = "Fibra Uno",
                            SiteUrl = "https://fibra.uno",
                            State = "Active",
                            Ticker = "FUNO11",
                            YahooTicker = "FUNO11.MX"
                        },
                        new
                        {
                            Id = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Danhos",
                            InvestorUrl = "https://fibradanhos.com.mx/ri",
                            Market = "BMV",
                            NameVariants = "[\"Danhos\",\"DANHOS\"]",
                            Sector = "Comercial",
                            ShortName = "Danhos",
                            SiteUrl = "https://fibradanhos.com.mx",
                            State = "Active",
                            Ticker = "DANHOS13",
                            YahooTicker = "DANHOS13.MX"
                        },
                        new
                        {
                            Id = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Terra",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Terra\",\"TERRA\"]",
                            Sector = "Industrial",
                            ShortName = "Terra",
                            SiteUrl = "https://fibra-terra.com",
                            State = "Active",
                            Ticker = "TERRA13",
                            YahooTicker = "TERRA13.MX"
                        },
                        new
                        {
                            Id = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Macquarie",
                            InvestorUrl = "https://fibramacquarie.com.mx/ri",
                            Market = "BMV",
                            NameVariants = "[\"Fibra MQ\",\"Macquarie\",\"FIBRAMQ\"]",
                            Sector = "Industrial",
                            ShortName = "FibraMQ",
                            SiteUrl = "https://fibramacquarie.com.mx",
                            State = "Active",
                            Ticker = "FIBRAMQ12",
                            YahooTicker = "FIBRAMQ12.MX"
                        },
                        new
                        {
                            Id = new Guid("7882f6d3-304f-5de6-2211-60508c2021c6"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Monterrey",
                            InvestorUrl = "https://fibramty.com/inversionistas",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Monterrey\",\"FibraMTY\",\"FMTY\"]",
                            Sector = "Industrial",
                            ShortName = "Fibra MTY",
                            SiteUrl = "https://fibramty.com",
                            State = "Active",
                            Ticker = "FMTY14",
                            YahooTicker = "FMTY14.MX"
                        },
                        new
                        {
                            Id = new Guid("38a237f5-9065-f4ec-7b19-c116a9642c6f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Inn",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Inn\",\"FINN\"]",
                            Sector = "Hotelero",
                            ShortName = "Fibra Inn",
                            SiteUrl = "https://fibrainn.com.mx",
                            State = "Active",
                            Ticker = "FINN13",
                            YahooTicker = "FINN13.MX"
                        },
                        new
                        {
                            Id = new Guid("6cbe26c2-2ed0-6df0-6242-1c78d011e9fc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Hotel",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Hotel\",\"FIHO\"]",
                            Sector = "Hotelero",
                            ShortName = "Fibra Hotel",
                            SiteUrl = "https://fibrahotel.com",
                            State = "Active",
                            Ticker = "FIHO12",
                            YahooTicker = "FIHO12.MX"
                        },
                        new
                        {
                            Id = new Guid("ae26cf6f-b4dc-be5a-3355-f4f4a9165499"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Vesta",
                            InvestorUrl = "https://fibravesta.com/ri",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Vesta\",\"VESTA\"]",
                            Sector = "Industrial",
                            ShortName = "Vesta",
                            SiteUrl = "https://fibravesta.com",
                            State = "Active",
                            Ticker = "VESTA15",
                            YahooTicker = "VESTA.MX"
                        },
                        new
                        {
                            Id = new Guid("d96dd899-9a7e-3c95-a9ba-bbf62577a241"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Hotel City Express",
                            Market = "BMV",
                            NameVariants = "[\"Hotel City Express\",\"HCITY\",\"HC\"]",
                            Sector = "Hotelero",
                            ShortName = "HC",
                            SiteUrl = "https://hcity.com.mx",
                            State = "Active",
                            Ticker = "HCITY17",
                            YahooTicker = "HCITY.MX"
                        },
                        new
                        {
                            Id = new Guid("cc194e75-e5a3-ee5e-0673-0f61be3fe509"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "MXN",
                            FullName = "Fibra Plus",
                            Market = "BMV",
                            NameVariants = "[\"Fibra Plus\",\"PLUS\"]",
                            Sector = "Diversificado",
                            ShortName = "Fibra Plus",
                            SiteUrl = "https://fibraplus.mx",
                            State = "Active",
                            Ticker = "PLUS18",
                            YahooTicker = "PLUS18.MX"
                        });
                });

            modelBuilder.Entity("Domain.Market.DailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("close");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("high");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("open");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("FibraId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_DailySnapshot_FibraId_Date");

                    b.ToTable("DailySnapshot", "market");
                });

            modelBuilder.Entity("Domain.Market.Distribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPerUnit")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("amount_per_unit");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("FibraId", "PaymentDate")
                        .HasDatabaseName("IX_Distribution_FibraId_PaymentDate");

                    b.ToTable("Distribution", "market");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b34cecad-3540-7d2b-5ea6-8000db9c5a0b"),
                            AmountPerUnit = 0.3610m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 3, 17),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("0712aff6-cf0f-55dd-a6dc-090e83c5233a"),
                            AmountPerUnit = 0.3720m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 6, 16),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("85a4ed94-b620-298c-c457-b124599fb3b7"),
                            AmountPerUnit = 0.3780m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("c36fa6a1-117f-9d25-a947-8d6ee00e30f4"),
                            AmountPerUnit = 0.3840m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("7347fc56-b1d8-1853-7712-ac4dc204564c"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "FUNO11"
                        },
                        new
                        {
                            Id = new Guid("3ad4a8a2-8e06-5923-aedd-25a49939ea84"),
                            AmountPerUnit = 0.2150m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 3, 17),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("ac5bb4bb-0719-2425-d621-5f823e9da129"),
                            AmountPerUnit = 0.2200m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 6, 16),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("e95c49b8-0da1-0cdb-9698-4ffee01cb629"),
                            AmountPerUnit = 0.2250m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("f2af8992-b244-6d43-9610-2f69c170477f"),
                            AmountPerUnit = 0.2300m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("5d911406-8042-d1db-90b0-6c5aebb882bf"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "DANHOS13"
                        },
                        new
                        {
                            Id = new Guid("52cae36d-59cc-bc56-cb33-cb5429192916"),
                            AmountPerUnit = 0.1750m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2025, 6, 16),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("8671a635-0d04-2660-ae19-dac73d60fd1b"),
                            AmountPerUnit = 0.1800m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("4f56248a-fe67-33bf-4033-6df6a608ca2b"),
                            AmountPerUnit = 0.1820m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("894a2120-2ad3-d3f4-44fd-0d0c423b849f"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "TERRA13"
                        },
                        new
                        {
                            Id = new Guid("b2b41c08-7711-6ede-c2f0-8936c7a72828"),
                            AmountPerUnit = 0.1480m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2025, 9, 15),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        },
                        new
                        {
                            Id = new Guid("3fce78aa-5887-0f04-a1f3-ca1e7fcb4803"),
                            AmountPerUnit = 0.1520m,
                            CapturedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MXN",
                            FibraId = new Guid("2799e174-1233-93ba-87ce-ade15c0c4010"),
                            PaymentDate = new DateOnly(2025, 12, 15),
                            Source = "seed",
                            Ticker = "FIBRAMQ12"
                        });
                });

            modelBuilder.Entity("Domain.Market.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<decimal?>("DailyChange")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("daily_change");

                    b.Property<decimal?>("DailyChangePct")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("daily_change_pct");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("error_reason");

                    b.Property<Guid>("FibraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fibra_id");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("last_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticker");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("week52_high");

                    b.Property<decimal?>("Week52Low")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("week52_low");

                    b.HasKey("Id");

                    b.HasIndex("FibraId", "CapturedAt")
                        .HasDatabaseName("IX_PriceSnapshot_FibraId_CapturedAt");

                    b.ToTable("PriceSnapshot", "market");
                });

            modelBuilder.Entity("Domain.News.BlocklistTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.HasIndex("Term")
                        .IsUnique()
                        .HasDatabaseName("IX_BlocklistTerm_Term");

                    b.ToTable("BlocklistTerm", "news");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e42a6f48-fd39-9fcb-9cdd-b32936d4151a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra óptica"
                        },
                        new
                        {
                            Id = new Guid("e05324fb-2c04-9389-41f6-a1dce885eba2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra optica"
                        },
                        new
                        {
                            Id = new Guid("33addac2-f65d-b0e1-616f-0b72e7aad6c3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra alimentaria"
                        },
                        new
                        {
                            Id = new Guid("93629cda-318e-f05f-94a4-49e87f7a07b3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra dietética"
                        },
                        new
                        {
                            Id = new Guid("3c3dbbea-5d57-c2e7-7395-0cef7bf9fba9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra dietetica"
                        },
                        new
                        {
                            Id = new Guid("c0166b06-2573-7815-6d80-6e448212bc1a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra muscular"
                        },
                        new
                        {
                            Id = new Guid("18288ba5-5469-5321-b116-12f462def773"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra textil"
                        },
                        new
                        {
                            Id = new Guid("01198b97-3348-19ce-d5a6-92bbde33ebeb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra de carbono"
                        },
                        new
                        {
                            Id = new Guid("e1e5c21c-7dcc-13b9-c5b2-065e293260cd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "internet fibra"
                        },
                        new
                        {
                            Id = new Guid("c2c16834-61c4-a329-acb9-3f601fe94781"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Term = "fibra de vidrio"
                        });
                });

            modelBuilder.Entity("Domain.News.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("error_reason");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<string>("Snippet")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("snippet");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title");

                    b.Property<string>("TitleNormalized")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("title_normalized");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsArticle_Url");

                    b.HasIndex("TitleNormalized", "CapturedAt")
                        .HasDatabaseName("IX_NewsArticle_TitleNormalized_CapturedAt");

                    b.ToTable("NewsArticle", "news");
                });

            modelBuilder.Entity("Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("Domain.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
