using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddEditorialPages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "EditorialPage",
                schema: "ops",
                columns: table => new
                {
                    slug = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    content = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    display_order = table.Column<int>(type: "int", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EditorialPage", x => x.slug);
                });

            migrationBuilder.InsertData(
                schema: "ops",
                table: "EditorialPage",
                columns: new[] { "slug", "content", "display_order", "title", "updated_at" },
                values: new object[,]
                {
                    { "como-se-estructuran", "## La arquitectura jurídica de una FIBRA\n\nUna FIBRA existe como un **fideicomiso irrevocable**. El fideicomiso es el propietario legal de los inmuebles y el emisor de los CBFIs.\n\n### Actores principales\n\n- **Fideicomitentes**: aportan inmuebles o efectivo al vehículo\n- **Fiduciario**: institución financiera que mantiene la titularidad legal\n- **Fideicomisarios**: tenedores de CBFIs\n- **Administrador**: opera inmuebles, cobra rentas y ejecuta la estrategia\n- **Comité Técnico**: órgano de gobierno equivalente a un consejo\n\n### Asamblea de Tenedores\n\nEs el máximo órgano de decisión. Cada CBFI representa derechos económicos y, en los supuestos aplicables, derechos de voto.\n\n### Reguladores relevantes\n\n| Autoridad | Función |\n|---|---|\n| **CNBV** | Supervisión del mercado y obligaciones de revelación |\n| **BMV / BIVA** | Listado y negociación secundaria |\n| **SAT** | Vigilancia del cumplimiento del régimen fiscal especial |\n\n### Distribución mínima del 95%\n\nEl requisito de distribuir al menos el **95% del resultado fiscal** es uno de los rasgos más distintivos del instrumento. Esto obliga a que gran parte del flujo llegue a los inversionistas de forma periódica.\n\n### FIBRA inmobiliaria vs FIBRA E\n\nLas FIBRAs inmobiliarias invierten en bienes raíces para arrendamiento. Las **FIBRA E** monetizan flujos o activos de energía e infraestructura, pero comparten la lógica de vehículo listado y tratamiento fiscal especializado.", 3, "¿Cómo se estructuran?", new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                    { "historia", "## De la regulación al mercado\n\nLas reglas iniciales para este tipo de instrumento surgieron en 2004, pero fue hasta **2011** cuando el mercado tomó forma con la salida a bolsa de **FIBRA Uno (FUNO11)**.\n\n### 18 de marzo de 2011: el primer CBFI\n\nFUNO11 realizó su Oferta Pública Inicial con un portafolio inicial de 16 inmuebles y un precio de salida de **19.50 pesos por CBFI**. Ese evento marcó el nacimiento formal del mercado de FIBRAs en México.\n\n### Expansión 2012–2014\n\nDespués de FUNO llegaron vehículos especializados en hotelería, industria y retail. También comenzaron adquisiciones de gran escala que consolidaron al instrumento como una fuente relevante de capital inmobiliario.\n\n### Consolidación 2015–2019\n\nEn 2015 se formalizó el índice **S&P/BMV FIBRAS**, y ese mismo año surgió el concepto de **FIBRA E** para energía e infraestructura. Esto amplió el universo de activos securitizables bajo la misma lógica de distribuciones recurrentes.\n\n### Prueba de estrés: pandemia 2020\n\nLa pandemia afectó sobre todo a los segmentos comercial y hotelero. Las industriales resistieron mejor y posteriormente se beneficiaron del nearshoring.\n\n### Mercado maduro 2021–2025\n\nPara 2025 el sector acumulaba cientos de miles de millones de pesos en activos administrados, miles de propiedades y una ocupación promedio robusta. El instrumento dejó de ser experimental y pasó a ser una categoría establecida dentro del mercado público mexicano.", 2, "Historia", new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                    { "por-que-invertir", "## Razones para considerar FIBRAs en un portafolio\n\n### Acceso al inmobiliario institucional\n\nComprar directamente un inmueble institucional exige mucho capital, poca diversificación y gestión operativa. Las FIBRAs permiten exposición a ese mercado con tickets significativamente menores.\n\n### Liquidez bursátil\n\nUn inmueble directo puede tardar meses en venderse. Un CBFI puede comprarse o venderse en bolsa en tiempo real durante la sesión del mercado.\n\n### Distribuciones periódicas\n\nEl sector ha sido atractivo históricamente por su capacidad de entregar distribuciones recurrentes. El rendimiento exacto cambia por emisora, tasas y valuaciones, pero el marco obliga a repartir flujo.\n\n### Diversificación y gestión profesional\n\nCon un solo instrumento puedes acceder a múltiples inmuebles, ciudades, inquilinos y segmentos. Además, la administración corre por cuenta de equipos especializados.\n\n---\n\n## Riesgos reales\n\nNinguna tesis de inversión está completa sin riesgos claros:\n\n- **Tasas de interés**: cuando suben, los CBFIs suelen presionarse\n- **Vacancia**: menos ocupación implica menos flujo\n- **Tipo de cambio**: relevante en portafolios dolarizados\n- **Dilución**: nuevas emisiones pueden reducir rendimiento por certificado\n- **Gobierno corporativo**: la alineación del administrador importa\n\nEl análisis debe considerar tanto yield como calidad del portafolio, deuda, ocupación y disciplina de capital.", 4, "Por qué invertir", new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                    { "que-son-las-fibras", "## Fideicomisos de Inversión en Bienes Raíces\n\nLas FIBRAs son vehículos de inversión que permiten a cualquier persona participar en el mercado inmobiliario institucional mexicano sin necesidad de comprar propiedades directamente. Son fideicomisos constituidos conforme a la Ley General de Títulos y Operaciones de Crédito, con régimen fiscal especial regulado en los artículos 187 y 188 de la Ley del Impuesto Sobre la Renta (LISR).\n\n## ¿Cómo funciona un fideicomiso FIBRA?\n\nEl fideicomiso adquiere y administra inmuebles que generan renta: centros comerciales, parques industriales, hoteles, oficinas corporativas y almacenes logísticos. Los inversionistas compran **CBFIs** (Certificados Bursátiles Fiduciarios Inmobiliarios) en la BMV o en la BIVA. Las rentas cobradas a los inquilinos, menos gastos operativos y deuda, se distribuyen entre los tenedores en proporción a su participación.\n\nPara calificar como FIBRA y acceder al régimen fiscal preferente, el fideicomiso debe cumplir tres requisitos estructurales:\n\n- **Mínimo 70%** del patrimonio invertido en inmuebles para arrendamiento\n- Los inmuebles deben permanecer en el fideicomiso al menos **cuatro años**\n- Distribuir al menos el **95% del resultado fiscal anual**\n\n## Los CBFIs: qué son y cómo se negocian\n\nUn CBFI representa una participación en el patrimonio del fideicomiso. No es una acción tradicional; da derecho a recibir distribuciones, participar en la apreciación del portafolio y votar en asambleas de tenedores.\n\nLos tickers bursátiles siguen la convención de combinar el nombre abreviado con un número de serie: FUNO11, FMTY14, FIBRAPL14 o DANHOS13. Esto permite que inversionistas individuales entren al sector con montos pequeños comparados con la compra directa de inmuebles.\n\n## Tipos de inmuebles\n\n| Segmento | Características clave |\n|---|---|\n| **Industrial y logístico** | Naves manufactureras, parques industriales y centros de distribución |\n| **Comercial** | Centros comerciales y plazas de retail |\n| **Corporativo** | Oficinas clase A en principales ciudades |\n| **Hotelero** | Hoteles de negocios y resorts |\n| **Mixto** | Combinación de varios segmentos |\n\n## ¿En qué se diferencian de los REITs de EE.UU.?\n\nLas FIBRAs son el equivalente mexicano de los REITs. Comparten la obligación de distribuir la mayor parte del flujo, pero en México operan como fideicomisos y cuentan con un tratamiento fiscal local específico.\n\n## ¿Quién puede invertir?\n\nCualquier persona física o moral con acceso a una casa de bolsa o plataforma de inversión puede comprar CBFIs. También participan Afores, aseguradoras y fondos institucionales, lo que aporta profundidad al mercado.", 1, "¿Qué son las FIBRAs?", new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) },
                    { "regimen-fiscal", "## Tratamiento fiscal general de las FIBRAs\n\n> Esta sección es educativa y no sustituye asesoría fiscal profesional.\n\n### Transparencia fiscal del fideicomiso\n\nEl fideicomiso determina un resultado fiscal y lo distribuye a los tenedores. El tratamiento final depende del tipo de inversionista.\n\n### Personas físicas residentes en México\n\nEn términos generales, las distribuciones provenientes del resultado fiscal están sujetas a retención provisional. Una parte puede corresponder a reembolso de capital, con tratamiento distinto al momento del cobro.\n\n### Ganancia de capital en bolsa\n\nUno de los atributos más relevantes es que, bajo las condiciones aplicables, la ganancia por venta bursátil de CBFIs puede tener un tratamiento fiscal más favorable que otros instrumentos patrimoniales.\n\n### Personas morales, fondos y extranjeros\n\nEl efecto fiscal cambia según si el inversionista es persona moral, fondo de pensiones o residente en el extranjero. Siempre conviene revisar el régimen concreto y, si aplica, tratados internacionales.\n\n### Resumen práctico\n\n| Tipo de inversionista | Distribuciones | Venta bursátil |\n|---|---|---|\n| Persona física residente | Retención provisional y acumulación anual | Tratamiento fiscal específico del régimen FIBRA |\n| Persona moral residente | Acumulación corporativa | Depende del régimen aplicable |\n| Fondos elegibles | Beneficios particulares bajo reglas específicas | Revisar reglas del vehículo |\n| Extranjero | Sujeto a retenciones o tratado | Depende de LISR y tratado |\n\nAntes de invertir, conviene entender si tu tesis depende del flujo distribuido, de la apreciación de capital o de ambas.", 5, "Régimen fiscal", new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)) }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EditorialPage",
                schema: "ops");
        }
    }
}
